language: node_js
node_js: "stable"

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
# npm install --save-dev jest
before_install:
  - npm i -g npm@6.14.8

script: cd ./backend && npm install && npm test -- schedule.test.js label.test.js