language: node_js
node_js: "stable"

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - npm i -g npm@6.14.8 && npm install --save-dev jest

script: cd ./backend && npm test -- schedule.test.js label.test.js